### ISSUE TITLE
Add our website links

### ISSUE THREAD

**Issue by Ved-programmer** [crypto-navdeep/Pig-Latin#2]
I have created a pr to add our website links

**Comment by Ved-programmer** [comment]
this will help our websites in SEO

**Comment by crypto-navdeep** [comment]
Hi Ved, Checked You're PR, I am actually developing the footer where I would add all the links but I have accepted you're PR so that there would be a temporary footer. I'll keep this issue open till I develop the footer (won't take much time).

**Comment by Ved-programmer** [comment]
ok
